services:

  django-web:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    networks:
      - augur-net

  django-migrate:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    command: uv run manage.py migrate --noinput
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - augur-net
    profiles:
      - commands

  django-createsuperuser:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    command: uv run manage.py createsuperuser --noinput --username admin --email admin@example.com
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - augur-net
    profiles:
      - commands

  postgres-db:
    image: edrodefeld/atlas
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U atlas_user -d atlas" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      - POSTGRES_DB=augur
      - POSTGRES_USER=atlas_user
      - POSTGRES_PASSWORD=atlas_password
    networks:
      - augur-net

volumes:
  postgres-db-volume:


networks:
  augur-net:
    name: augur-net
    driver: bridge
