# Generated by Django 5.1 on 2025-12-10 05:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('collection', models.CharField(blank=True, default='', max_length=256)),
                ('provider', models.CharField(blank=True, default='', max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, default='', max_length=256)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('metadata', models.CharField(blank=True, default='', max_length=4096)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveLookupStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveLookupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('metadata', models.CharField(blank=True, default='', max_length=65536)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.collection')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery_finder.archivelookupstudy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageryFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rules', models.CharField(blank=True, default='', max_length=65536)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='archivelookupstudy',
            name='imagery_finder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery_finder.imageryfinder'),
        ),
        migrations.CreateModel(
            name='ArchiveLookupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('archive_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagery_finder.archiveitem')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery_finder.archivelookupstudy')),
                ('imagery_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery_finder.imageryfinder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
