# Generated by Django 5.1 on 2025-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2048),
        ),
    ]
