# Generated by Django 5.1 on 2025-12-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_finder', '0002_alter_archiveitem_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['external_id'], name='archiveitem_external_id_idx'),
        ),
    ]
