# Generated by Django 5.1 on 2025-11-20 19:53

import django.db.models.deletion
from django.db import migrations, models


def create_locations_from_geometry(apps, schema_editor):
    ArchiveFinder = apps.get_model("archive_finder", "ArchiveFinder")
    Location = apps.get_model("core", "Location")
    User = apps.get_model("core", "User")

    user = User.objects.order_by("id").first()
    if user is None:
        user = User.objects.create(username="archive_finder_migration_user", password="!")

    for finder in ArchiveFinder.objects.all():
        geometry = getattr(finder, "geometry", None)
        if geometry is None:
            continue

        location = Location.objects.create(
            name=finder.name or f"Archive Finder {finder.pk}",
            geometry=geometry,
            user=user,
        )
        finder.location = location
        finder.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0012_remove_imagerylookupresult_imagery_lookup_study_and_more'),
        ('core', '0010_location_delete_imageryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefinder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.RunPython(create_locations_from_geometry, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='archivefinder',
            name='geometry',
        ),
        migrations.AlterField(
            model_name='archivefinder',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
