# Generated by Django 5.1 on 2025-11-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0013_remove_archivefinder_geometry_archivefinder_location'),
        ('core', '0010_location_delete_imageryrequest'),
        ('provider', '0004_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLookupStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='imagerylookupstudy',
            name='archive_finder',
        ),
        migrations.RemoveField(
            model_name='imagerylookupitem',
            name='archive_finder',
        ),
        migrations.RemoveField(
            model_name='imagerylookupitem',
            name='archive_item',
        ),
        migrations.RemoveField(
            model_name='imagerylookupitem',
            name='study',
        ),
        migrations.RenameModel(
            old_name='ImageryLookupResult',
            new_name='ArchiveLookupResult',
        ),
        migrations.AlterField(
            model_name='archivelookupresult',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archivelookupstudy'),
        ),
        migrations.CreateModel(
            name='ImageryFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rules', models.CharField(blank=True, default='', max_length=65536)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='archivelookupstudy',
            name='imagery_finder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.imageryfinder'),
        ),
        migrations.CreateModel(
            name='ArchiveLookupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('archive_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_finder.archiveitem')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archivelookupstudy')),
                ('imagery_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.imageryfinder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ArchiveFinder',
        ),
        migrations.DeleteModel(
            name='ImageryLookupItem',
        ),
        migrations.DeleteModel(
            name='ImageryLookupStudy',
        ),
    ]
