# Generated by Django 5.1 on 2025-12-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='flow_run_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
